#!/bin/bash
#
# Make sure that old mcollective cruft is removed
# This also allows us to downgrade mcollective as
# it's more likely that installing old versions
# over new will cause issues.
#
# ${3} is the destination volume so that this works correctly
# when being installed to volumes other than the current OS.

# remove old doc files
/bin/rm -Rf "${3}/usr/share/doc/puppet"

# Clean the old mcollectived executable.
/bin/rm -Rf "${3}/usr/sbin/mcollectived"