#!/bin/bash
#
# Make sure that old mcollective cruft is removed
# This also allows us to downgrade mcollective as
# it's more likely that installing old versions
# over new will cause issues.
#
# ${3} is the destination volume so that this works correctly
# when being installed to volumes other than the current OS.

/bin/rm -Rf "${3}/usr/lib/ruby/site_ruby/1.8/mcollective"
/bin/rm -Rf "${3}/usr/lib/ruby/site_ruby/1.8/mcollective.rb"

# Remove old mcollective libexec directory
/bin/rm -Rf "${3}/usr/libexec/mcollective"

# Clean the old executables before installing new ones (if they exist).
/bin/rm -Rf "${3}/usr/sbin/mc-call-agent"
/bin/rm -Rf "${3}/usr/sbin/mc-controller"
/bin/rm -Rf "${3}/usr/sbin/mc-facts"
/bin/rm -Rf "${3}/usr/sbin/mc-find-hosts"
/bin/rm -Rf "${3}/usr/sbin/mc-inventory"
/bin/rm -Rf "${3}/usr/sbin/mc-ping"
/bin/rm -Rf "${3}/usr/sbin/mc-rpc"
/bin/rm -Rf "${3}/usr/sbin/mcollectived"