#!/bin/bash
#
# Make sure that old mcollective cruft is removed
# This also allows us to downgrade mcollective as
# it's more likely that installing old versions
# over new will cause issues.
#
# ${3} is the destination volume so that this works correctly
# when being installed to volumes other than the current OS.

# Remove old mcollective ruby libraries
/bin/rm -Rf "${3}/usr/lib/ruby/site_ruby/1.8/mcollective"
/bin/rm -Rf "${3}/usr/lib/ruby/site_ruby/1.8/mcollective.rb"

# Remove old mcollective libexec directory
/bin/rm -Rf "${3}/usr/libexec/mcollective"
