#
# Example showing how to package edu.mit.Kerberos in a package
#
# Author: Joe Block <jpb@ApesSeekingKnowledge.net>
# License: BSD

include /usr/local/share/luggage/luggage.make

TITLE=setup_kerberos
REVERSE_DOMAIN=com.example.corp

PAYLOAD=pack-Library-Preferences-edu.mit.Kerberos

