#!/bin/sh

# (c) 2010 Walter Meyer SUNY Purchase College

#  This script, and subsequent package, should ONLY BE RUN ON THE VOLUME
#   TO WHICH THE COMPUTER IS BOOTED!  Using this script in InstaDMG will cause
#   issues (printer is installed on InstaDMG computer, not IMAGED computer!).

# Script to install and setup printers on a Mac OS X system in a "Munki-Friendly" way.
# Make sure to install the required drivers first!

# Check to make sure we're ONLY installing to the boot volume
if [ "$3" != "/" ]; then
       exit 0
fi

# Variables. Edit these.
printername="psm_HHS_Office_9040"
location="HHS Office"
gui_display_name="HHS Main Office 9040 Fax Copier"
address="lpd://10.13.1.8/HHS_Office_9040_Fax_Printer"
driver_ppd="/Library/Printers/PPDs/Contents/Resources/HP LaserJet 9040.gz"

### Printer Install ###
# Install the printer.
/usr/sbin/lpadmin -p "$printername" -L "$location" -D "$gui_display_name" -v "$address" -P "$driver_ppd" -E -o printer-is-shared=false


# Enable and start the printers on the system (after adding the printer initially it is paused).
/usr/sbin/cupsenable $(lpstat -p | grep -w "printer" | awk '{print$2}')

# Set the printer as the default if we want.
# /usr/bin/lpoptions -d $printername

### Other Installs ###
# Make a directory we can use for storing our information files and uninstall scripts.
mkdir /private/etc/cups/printers_deployment
printer_conf="/private/etc/cups/printers_deployment/$printername"
/bin/echo "$printername" > "$printer_conf"
/bin/echo "$location" >> "$printer_conf"
/bin/echo "$gui_display_name" >> "$printer_conf"
/bin/echo "$address" >> "$printer_conf"
/bin/echo "$driver_ppd" >> "$printer_conf"

# Create an uninstall script for the printer.
mkdir /private/etc/cups/printers_deployment/uninstalls
uninstall_script="/private/etc/cups/printers_deployment/uninstalls/$printername.sh"
/bin/echo "#!/bin/sh" > "$uninstall_script"
/bin/echo "/usr/sbin/lpadmin -x $printername" >> "$uninstall_script"
/bin/echo "srm /private/etc/cups/printers_deployment/$printername" >> "$uninstall_script"
/bin/echo "srm /private/etc/cups/printers_deployment/uninstalls/$printername.sh" >> "$uninstall_script"
/bin/echo "srm /private/etc/cups/ppd/$printername" >> "$uninstall_script"

# Permission the directories properly.
/usr/sbin/chown -R root:_lp /private/etc/cups/printers_deployment
/bin/chmod -R 700 /private/etc/cups/printers_deployment

exit 0